lxc.mount.entry: /data/lxcdata/fileutils/filebrowser filebrowserdata none bind,create=dir 0 0
lxc.mount.entry: /data/books/comics data/books/comics none bind,create=dir 0 0
lxc.mount.entry: /data/books/ebooks data/books/ebooks none bind,create=dir 0 0
lxc.mount.entry: /data/downloads data/downloads none bind,create=dir 0 0
lxc.mount.entry: /data/installers/ISOs data/installers/ISOs none bind,create=dir 0 0
lxc.mount.entry: /data/installers/programs data/installers/programs none bind,create=dir 0 0
lxc.mount.entry: /data/media/animes data/media/animes none bind,create=dir 0 0
lxc.mount.entry: /data/media/doramas data/media/doramas none bind,create=dir 0 0
lxc.mount.entry: /data/media/movies data/media/movies none bind,create=dir 0 0
lxc.mount.entry: /data/media/novelas data/media/novelas none bind,create=dir 0 0
lxc.mount.entry: /data/media/series data/media/series none bind,create=dir 0 0
lxc.mount.entry: /data/media/videos data/media/videos none bind,create=dir 0 0
lxc.mount.entry: /data/music data/music none bind,create=dir 0 0
lxc.mount.entry: /data/personaldata data/personaldata none bind,create=dir 0 0
lxc.mount.entry: /data/pics/familypics data/pics/familypics none bind,create=dir 0 0
lxc.mount.entry: /data/pics/personalpics data/pics/personalpics none bind,create=dir 0 0
