version: "3"

secrets:
  CLOUDFLARED_TOKEN:
    file: ./secrets/cloudflared_token.txt

services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    secrets:
      - CLOUDFLARED_TOKEN
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/CLOUDFLARED_TOKEN
