lxc.mount.entry: /data/lxcdata/media lxcmedia none bind,create=dir 0 0
lxc.mount.entry: /data/lxcdata/pics lxcpics none bind,create=dir 0 0
lxc.mount.entry: /data/media/animes data/media/animes none bind,create=dir 0 0
lxc.mount.entry: /data/media/doramas data/media/doramas none bind,create=dir 0 0
lxc.mount.entry: /data/media/movies data/media/movies none bind,create=dir 0 0
lxc.mount.entry: /data/media/novelas data/media/novelas none bind,create=dir 0 0
lxc.mount.entry: /data/media/series data/media/series none bind,create=dir 0 0
lxc.mount.entry: /data/media/videos data/media/videos none bind,create=dir 0 0
lxc.mount.entry: /data/pics/familypics data/pics/familypics none bind,create=dir 0 0
lxc.mount.entry: /data/pics/personalpics data/pics/personalpics none bind,create=dir 0 0
dev0: /dev/dri/renderD128,gid=993